apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hm-soknadsbehandling-db
    team: teamdigihot
  name: hm-soknadsbehandling-db
  namespace: teamdigihot
spec:
  image: {{ image }}
  ingresses:
    - https://hm-soknadsbehandling-db.intern.dev.nav.no
  envFrom:
    - secret: hm-slack-hook
  kafka:
    pool: nav-dev
  liveness:
    path: /is_alive
    initialDelay: 30
    timeout: 100
  readiness:
    path: /is_ready
    initialDelay: 30
    timeout: 100
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    max: 1
    min: 1
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: hm-dinehjelpemidler
        - application: hm-forslagsmotor-tilbehoer
        - application: hm-formidler
        - application: hm-kommune-api
        - application: hm-soknadsbehandling
        - application: hm-oppgave-sink
        - application: hm-saksfordeling
        - application: hm-saksbehandling
        - application: azure-token-generator
          namespace: aura
          cluster: dev-gcp
        - application: tokenx-token-generator
          namespace: aura
          cluster: dev-gcp
    outbound:
      rules:
        - application: hm-grunndata-search
        - application: hm-roller
        - application: logging
          namespace: nais-system
      external:
        - host: hooks.slack.com
        - host: safselvbetjening.dev-fss-pub.nais.io
  resources:
    limits:
      cpu: 800m
      memory: 2024Mi
    requests:
      cpu: 10m
      memory: 512Mi
  gcp:
    sqlInstances:
      - name: hm-soknadsbehandling-v4-db-dev
        type: POSTGRES_15
        tier: db-f1-micro
        diskType: SSD
        highAvailability: false
        diskSize: 10
        diskAutoresize: true
        autoBackupHour: 3
        databases:
          - name: soknadsbehandling-v4-db-dev
            envVarPrefix: DB
        cascadingDelete: false
    bigQueryDatasets:
      - name: hm_soknadsbehandling_v1_dataset_dev
        permission: READWRITE
  env:
    - name: PORT
      value: "8080"
    - name: KAFKA_TOPIC
      value: teamdigihot.hm-soknadsbehandling-v1
    - name: GRUNNDATA_API_URL
      value: http://hm-grunndata-search/graphql
    - name: HM_ROLLER_URL
      value: http://hm-roller
    - name: HM_ROLLER_AUDIENCE
      value: dev-gcp:teamdigihot:hm-roller
    - name: SAFSELVBETJENING_URL
      value: https://safselvbetjening.dev-fss-pub.nais.io
    - name: SAFSELVBETJENING_AUDIENCE
      value: dev-fss:teamdokumenthandtering:safselvbetjening
    - name: BIGQUERY_DATASET_ID
      value: hm_soknadsbehandling_v1_dataset_dev
