apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hm-soknadsbehandling-db
    team: teamdigihot
  name: hm-soknadsbehandling-db
  namespace: teamdigihot
spec:
  image: {{ image }}
  envFrom:
    - secret: hm-slack-hook
  kafka:
    pool: nav-prod
  liveness:
    path: /is_alive
    initialDelay: 30
    timeout: 100
  readiness:
    path: /is_ready
    initialDelay: 30
    timeout: 100
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    max: 2
    min: 2
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  leaderElection: true
  accessPolicy:
    inbound:
      rules:
        - application: hm-dinehjelpemidler
        - application: hm-forslagsmotor-tilbehoer
        - application: hm-infotrygd-poller
        - application: hm-formidler
        - application: hm-kommune-api
        - application: hm-soknadsbehandling
        - application: hm-oppgave-sink
        - application: hm-saksfordeling
        - application: hm-saksbehandling
        - application: hm-soknad
    outbound:
      rules:
        - application: hm-grunndata-search
        - application: hm-roller
        - application: logging
          namespace: nais-system
      external:
        - host: hooks.slack.com
        - host: safselvbetjening.prod-fss-pub.nais.io
        - host: login.microsoftonline.com
        - host: graph.microsoft.com
  resources:
    limits:
      cpu: 800m
      memory: 2024Mi
    requests:
      cpu: 30m
      memory: 512Mi
  gcp:
    sqlInstances:
      - name: hm-soknadsbehandling-db-v3-prod
        type: POSTGRES_15
        tier: db-custom-2-7680
        diskType: SSD
        highAvailability: true
        diskSize: 20
        diskAutoresize: true
        autoBackupHour: 3
        databases:
          - name: hm-soknadsbehandling-db-v3-prod
            envVarPrefix: DB
        cascadingDelete: false
        pointInTimeRecovery: true
        flags:
          - name: "cloudsql.enable_pgaudit"
            value: "on"
          - name: "pgaudit.log"
            value: "write"
          - name: "pgaudit.log_parameter"
            value: "on"
    bigQueryDatasets:
      - name: hm_soknadsbehandling_v1_dataset_prod
        permission: READWRITE
  env:
    - name: PORT
      value: "8080"
    - name: KAFKA_TOPIC
      value: teamdigihot.hm-soknadsbehandling-v1
    - name: GRUNNDATA_API_URL
      value: http://hm-grunndata-search/graphql
    - name: HM_ROLLER_URL
      value: http://hm-roller
    - name: HM_ROLLER_AUDIENCE
      value: prod-gcp:teamdigihot:hm-roller
    - name: SAFSELVBETJENING_URL
      value: https://safselvbetjening.prod-fss-pub.nais.io
    - name: SAFSELVBETJENING_AUDIENCE
      value: prod-fss:teamdokumenthandtering:safselvbetjening
    - name: BIGQUERY_DATASET_ID
      value: hm_soknadsbehandling_v1_dataset_prod
