ALTER TABLE V1_SOKNAD ADD COLUMN ER_DIGITAL BOOLEAN;
UPDATE V1_SOKNAD SET ER_DIGITAL=TRUE WHERE ER_DIGITAL IS NULL;
ALTER TABLE V1_SOKNAD ALTER COLUMN FNR_INNSENDER DROP NOT NULL;
ALTER TABLE V1_SOKNAD ALTER COLUMN ER_DIGITAL SET NOT NULL;