ALTER TABLE V1_OEBS_DATA ADD COLUMN HJELPEMIDDELTYPE TEXT NULL;
UPDATE V1_OEBS_DATA SET HJELPEMIDDELTYPE = DATA ->> 'hjelpemiddeltype';
ALTER TABLE V1_OEBS_DATA ALTER COLUMN HJELPEMIDDELTYPE SET NOT NULL;