CREATE TABLE IF NOT EXISTS V1_VARSEL_BRUKERBEKREFTELSE
(
    ID                SERIAL PRIMARY KEY NOT NULL,
    FORMIDLER_EPOST   VARCHAR(254)       NOT NULL,
    TIDSPUNKT_VARSLET TIMESTAMPTZ        NOT NULL default (now())
);

CREATE INDEX V1_VARSEL_BRUKERBEKREFTELSE_TIDSPUNKT_VARSLET_IDX ON V1_VARSEL_BRUKERBEKREFTELSE (TIDSPUNKT_VARSLET);

CREATE TABLE IF NOT EXISTS V1_VARSEL_BRUKERBEKREFTELSE_BEHOVSMELDING
(
    ID               SERIAL PRIMARY KEY NOT NULL,
    VARSEL_ID        INTEGER REFERENCES V1_VARSEL_BRUKERBEKREFTELSE (ID),
    BEHOVSMELDING_ID UUID               NOT NULL
);