apiVersion: nais.io/v1
kind: Alert
metadata:
  name: hm-soknadsbehandling-db
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  alerts:
    - action: Sjekk {{ $labels.app }} i {{ $labels.kubernetes_namespace }} sine selftest
        for å se hva som er galt
      alert: feil i selftest
      expr: selftests_aggregate_result_status{app="hm-soknadsbehandling-db"} > 0
      for: 1m
  receivers:
    slack:
      channel: '#digihot-rr-alerts'
      prependText: '<!here> | '
