apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hm-soknadsbehandling-db
    team: teamdigihot
  name: hm-soknadsbehandling-db
  namespace: teamdigihot
spec:
  image: {{ image }}
  team: teamdigihot
  strategy:
    type: RollingUpdate
  liveness:
    path: /internal/is_alive
    initialDelay: 50
  readiness:
    path: /internal/is_ready
  port: 8080
  prometheus:
    enabled: true
    path: /internal/metrics
  replicas:
    max: 2
    min: 2
  accessPolicy:
    inbound:
      rules:
        - application: hm-brukerbekreftelse
        - application: hm-formidler
  tokenx:
    enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  secureLogs:
    enabled: true
  gcp:
    sqlInstances:
      - name: hm-soknadsbehandling-v2-db-dev
        type: POSTGRES_12
        tier: db-custom-1-3840
        diskType: SSD
        highAvailability: true
        diskSize: 10
        diskAutoresize: true
        autoBackupTime: "03:00"
        databases:
          - name: soknadsbehandling-v2-db-dev
            envVarPrefix: DB
        cascadingDelete: false

