apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hm-soknadsbehandling-db
    team: teamdigihot
  name: hm-soknadsbehandling-db
  namespace: teamdigihot
spec:
  image: {{ image }}
  team: teamdigihot
  envFrom:
    - secret: hm-influxdb-secret
  kafka:
    pool: nav-prod # just to get the SSL certificate required influxDB on GCP?
  liveness:
    path: /is_alive
    initialDelay: 30
    timeout: 100
  readiness:
    path: /is_ready
    initialDelay: 30
    timeout: 100
  port: 8080
  prometheus:
    enabled: true
    path: /internal/metrics
  replicas:
    max: 2
    min: 2
  accessPolicy:
    inbound:
      rules:
        - application: hm-dinehjelpemidler
        - application: hm-forslagsmotor-tilbehoer
        - application: hm-formidler
        - application: hm-soknadsbehandling
          namespace: teamdigihot
          cluster: prod-gcp
    outbound:
      rules:
        - application: hm-grunndata-api
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  resources:
    limits:
      cpu: 800m
      memory: 2024Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  secureLogs:
    enabled: true
  gcp:
    sqlInstances:
      - name: hm-soknadsbehandling-db-v3-prod
        type: POSTGRES_12
        tier: db-custom-4-15360
        diskType: SSD
        highAvailability: true
        diskSize: 20
        diskAutoresize: true
        autoBackupTime: "03:00"
        databases:
          - name: hm-soknadsbehandling-db-v3-prod
            envVarPrefix: DB
        cascadingDelete: false
  env:
    - name: PORT
      value: "8080"
    - name: KTOR_ENV
      value: production
