apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hm-soknadsbehandling-db
    team: teamdigihot
  name: hm-soknadsbehandling-db
  namespace: teamdigihot
spec:
  image: {{ image }}
  envFrom:
    - secret: hm-influxdb-secret
    - secret: hm-slack-hook
  kafka:
    pool: nav-dev
  liveness:
    path: /is_alive
    initialDelay: 30
    timeout: 100
  readiness:
    path: /is_ready
    initialDelay: 30
    timeout: 100
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    max: 1
    min: 1
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: hm-dinehjelpemidler
        - application: hm-forslagsmotor-tilbehoer
        - application: hm-formidler
        - application: hm-hjelpemiddelstatistikk
        - application: hm-kommune-api
        - application: hm-soknadsbehandling
          namespace: teamdigihot
          cluster: dev-gcp
    outbound:
      rules:
        - application: hm-grunndata-search
        - application: hm-roller
      external:
        - host: hooks.slack.com
  resources:
    limits:
      cpu: 800m
      memory: 2024Mi
    requests:
      cpu: 10m
      memory: 512Mi
  secureLogs:
    enabled: true
  gcp:
    sqlInstances:
      - name: hm-soknadsbehandling-v4-db-dev
        type: POSTGRES_15
        tier: db-f1-micro
        diskType: SSD
        highAvailability: false
        diskSize: 10
        diskAutoresize: true
        autoBackupHour: 3
        databases:
          - name: soknadsbehandling-v4-db-dev
            envVarPrefix: DB
        cascadingDelete: false
    bigQueryDatasets:
      - name: hm_soknadsbehandling_v1_dataset_dev
        permission: READWRITE
  env:
    - name: PORT
      value: "8080"
    - name: KTOR_ENV
      value: production
