apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hm-soknadsbehandling-db
    team: teamdigihot
  name: hm-soknadsbehandling-db
  namespace: teamdigihot
spec:
  image: {{ image }}
  team: teamdigihot
  envFrom:
    - secret: hm-influxdb-secret
  kafka:
    pool: nav-dev # just to get the SSL certificate required influxDB on GCP?
  liveness:
    path: /is_alive
    initialDelay: 30
    timeout: 1
    periodSeconds: 5
    failureThreshold: 3
  readiness:
    path: /is_ready
    initialDelay: 30
    timeout: 1
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    max: 1
    min: 1
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: hm-dinehjelpemidler
        - application: hm-formidler
        - application: hm-soknadsbehandling
          namespace: teamdigihot
          cluster: dev-gcp
    outbound:
      rules:
        - application: hm-grunndata-api
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  secureLogs:
    enabled: true
  gcp:
    sqlInstances:
      - name: hm-soknadsbehandling-v4-db-dev
        type: POSTGRES_12
        tier: db-custom-1-3840
        diskType: SSD
        highAvailability: true
        diskSize: 10
        diskAutoresize: true
        autoBackupTime: "03:00"
        databases:
          - name: soknadsbehandling-v4-db-dev
            envVarPrefix: DB
        cascadingDelete: false
  env:
    - name: PORT
      value: "8080"
    - name: KTOR_ENV
      value: production
