apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hm-soknadsbehandling-db
    team: teamdigihot
  name: hm-soknadsbehandling-db
  namespace: teamdigihot
spec:
  image: {{ image }}
  envFrom:
    - secret: hm-influxdb-secret
    - secret: hm-slack-hook
  kafka:
    pool: nav-prod
  liveness:
    path: /is_alive
    initialDelay: 30
    timeout: 100
  readiness:
    path: /is_ready
    initialDelay: 30
    timeout: 100
  port: 8080
  prometheus:
    enabled: true
    path: /internal/metrics
  replicas:
    max: 2
    min: 2
  accessPolicy:
    inbound:
      rules:
        - application: hm-dinehjelpemidler
        - application: hm-forslagsmotor-tilbehoer
        - application: hm-formidler
        - application: hm-hjelpemiddelstatistikk
        - application: hm-kommune-api
        - application: hm-soknadsbehandling
          namespace: teamdigihot
          cluster: prod-gcp
    outbound:
      rules:
        - application: hm-grunndata-search
        - application: hm-roller
      external:
        - host: hooks.slack.com
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  resources:
    limits:
      cpu: 800m
      memory: 2024Mi
    requests:
      cpu: 30m
      memory: 512Mi
  secureLogs:
    enabled: true
  gcp:
    sqlInstances:
      - name: hm-soknadsbehandling-db-v3-prod
        type: POSTGRES_15
        tier: db-custom-2-7680
        diskType: SSD
        highAvailability: true
        diskSize: 20
        diskAutoresize: true
        autoBackupHour: 3
        databases:
          - name: hm-soknadsbehandling-db-v3-prod
            envVarPrefix: DB
        cascadingDelete: false
    bigQueryDatasets:
      - name: hm_soknadsbehandling_v1_dataset_prod
        permission: READWRITE
  env:
    - name: PORT
      value: "8080"
    - name: KTOR_ENV
      value: production
