ALTER TABLE V1_SOKNAD ADD COLUMN STATUS VARCHAR(30);
UPDATE V1_SOKNAD SET STATUS = 'GODKJENT_MED_FULLMAKT' where STATUS IS NULL;
ALTER TABLE V1_SOKNAD ALTER COLUMN STATUS SET NOT NULL;
CREATE INDEX V1_SOKNAD_STATUS_BRUKER_IDX ON V1_SOKNAD (STATUS);
