CREATE TABLE IF NOT EXISTS V1_STATUS
(
    ID               SERIAL                   NOT NULL,
    SOKNADS_ID       UUID                     NOT NULL,
    STATUS           VARCHAR(30)              NOT NULL,
    CREATED          TIMESTAMP                NOT NULL default (now()),
    PRIMARY KEY (ID)
);

CREATE INDEX V1_STATUS_SOKNADS_ID_IDX ON V1_STATUS (SOKNADS_ID);

INSERT INTO V1_STATUS (SOKNADS_ID, STATUS) SELECT SOKNADS_ID, STATUS FROM V1_SOKNAD;

ALTER TABLE V1_SOKNAD DROP COLUMN STATUS;
