name: Deploy til prod-gcp

on:
  release:
    types: [ published ]

jobs:
  deploy-prod:
    permissions:
      contents: "write"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Sjekk ut koden

      - uses: nais/login@v0
        id: nais-login
        name: NAIS-login
        with:
          team: teamdigihot
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

      - name: "Definer $IMAGE"
        env:
          VERSION_TAG: ${{ github.event.release.tag_name }}
          REGISTRY: ${{ steps.nais-login.outputs.registry }}
          APP: ${{ github.event.repository.name }}
        run: |
          IMAGE=$REGISTRY/$APP:$VERSION_TAG
          echo "IMAGE=${IMAGE}" >> $GITHUB_ENV
          echo $IMAGE

      - uses: nais/deploy/actions/deploy@v1
        name: Deploy til prod-gcp
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/nais-prod.yaml,nais/alerts-prod.yaml

      - name: Post-deploy
        uses: navikt/digihot-deploy/actions/post-production@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
