name: Bygg, deploy til dev-gcp og lag release

on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENCE"
      - "CODEOWNERS"
    branches:
      - main

jobs:
  build:
    name: Bygg, deploy til dev-gcp og lag release
    permissions:
      packages: write
      contents: write
      id-token: write
    uses: navikt/hm-workflows/.github/workflows/deploy-dev.yaml@main
    with:
      manifest: .nais/nais-dev.yaml,.nais/alerts-dev.yaml
    secrets: inherit

  publish:
    if: github.ref == 'refs/heads/main'
    name: Publiser behovsmeldingsmodell
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      id-token: write

    steps:
      - name: Sjekk ut koden
        uses: actions/checkout@v4

      - name: Valider Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Sett opp Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Sett opp Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Publiser behovsmeldingsmodell
        run: ./gradlew :behovsmeldingsmodell:publish --no-daemon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
