name: Snyk scan dependencies
on: push
jobs:
  snyk-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/gradle-jdk16@master
      continue-on-error: true # To make sure that SARIF upload gets called
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: monitor
        args: --configuration-attributes=usage:java-runtime --project-name=${{ github.repository }} --remote-repo-url=https://github.com/${{ github.repository }}.git --org=hjelpemiddelbehov